name: deploy-pr

on:
    pull_request:
        paths:
            - 'app/**'
            - .github/workflows/deploy-pr.yml

jobs:
    build-and-push-image:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Docker meta
              id: meta
              uses: docker/meta-data-action@v5
              with:
                images: ghcr.io/${{ github.repository }}

            - name: Log in to GitHub container registry
              uses: docker/login-action@v3
              with:
                registry: ghcr.io
                username: ${{ github.actor }}
                password: ${{ secrets.GITHUB_TOKEN }}

            - name: Build and push
              uses: docker/build-push-action@v5
              with:
                context: app
                push: true
                tags: ${{ steps.meta.outputs.tags }}
                labels: ${{ steps.meta.outputs.labels }}



